// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForCreateTranslations implements pgx.CopyFromSource.
type iteratorForCreateTranslations struct {
	rows                 []CreateTranslationsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateTranslations) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateTranslations) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].EngName,
		r.rows[0].RuName,
		r.rows[0].ArmName,
	}, nil
}

func (r iteratorForCreateTranslations) Err() error {
	return nil
}

func (q *Queries) CreateTranslations(ctx context.Context, arg []CreateTranslationsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"translations"}, []string{"eng_name", "ru_name", "arm_name"}, &iteratorForCreateTranslations{rows: arg})
}
