// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dances.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDanceByID = `-- name: GetDanceByID :one
SELECT 
    d.id,
    d.complexity,
    d.photo_key,
    d.gender,
    d.paces,
    d.genres,
    d.handshakes,
    COALESCE(
        CASE 
            WHEN $2::text = 'ru' THEN t.ru_name
            WHEN $2::text = 'en' THEN t.eng_name
            WHEN $2::text = 'arm' THEN t.arm_name
            ELSE d.name
        END, 
        d.name
    )::text AS name,
    (SELECT COALESCE(json_agg(json_build_object('id', reg.id, 'name', reg.name)), '[]'::json)
     FROM regions reg
     JOIN dance_region dr ON dr.region_id = reg.id
     WHERE dr.dance_id = d.id) AS regions_json,
    (SELECT COALESCE(json_agg(json_build_object('id', v.id, 'name', v.name, 'link', v.link, 'type', v.type)), '[]'::json)
     FROM videos v
     JOIN dance_videos dv ON dv.video_id = v.id
     WHERE dv.dance_id = d.id) AS videos_json
FROM dances d
LEFT JOIN translations t ON d.translation_id = t.id
WHERE d.id = $1
`

type GetDanceByIDParams struct {
	ID   int64       `json:"id"`
	Lang pgtype.Text `json:"lang"`
}

type GetDanceByIDRow struct {
	ID          int64       `json:"id"`
	Complexity  pgtype.Int4 `json:"complexity"`
	PhotoKey    pgtype.Text `json:"photo_key"`
	Gender      string      `json:"gender"`
	Paces       []int32     `json:"paces"`
	Genres      []string    `json:"genres"`
	Handshakes  []string    `json:"handshakes"`
	Name        string      `json:"name"`
	RegionsJson interface{} `json:"regions_json"`
	VideosJson  interface{} `json:"videos_json"`
}

func (q *Queries) GetDanceByID(ctx context.Context, arg GetDanceByIDParams) (GetDanceByIDRow, error) {
	row := q.db.QueryRow(ctx, getDanceByID, arg.ID, arg.Lang)
	var i GetDanceByIDRow
	err := row.Scan(
		&i.ID,
		&i.Complexity,
		&i.PhotoKey,
		&i.Gender,
		&i.Paces,
		&i.Genres,
		&i.Handshakes,
		&i.Name,
		&i.RegionsJson,
		&i.VideosJson,
	)
	return i, err
}
