// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: init.sql

package db

import (
	"context"
)

const placeholder = `-- name: Placeholder :one
SELECT id, eng_name, ru_name, arm_name, created_at, updated_at FROM translations LIMIT 1
`

func (q *Queries) Placeholder(ctx context.Context) (Translation, error) {
	row := q.db.QueryRow(ctx, placeholder)
	var i Translation
	err := row.Scan(
		&i.ID,
		&i.EngName,
		&i.RuName,
		&i.ArmName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
