// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insert_translations.sql

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CreateTranslationsParams struct {
	EngName pgtype.Text `json:"eng_name"`
	RuName  pgtype.Text `json:"ru_name"`
	ArmName pgtype.Text `json:"arm_name"`
}
