// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Artist struct {
	ID            int64              `json:"id"`
	TranslationID pgtype.Int8        `json:"translation_id"`
	Name          string             `json:"name"`
	Link          string             `json:"link"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type Dance struct {
	ID            int64              `json:"id"`
	TranslationID pgtype.Int8        `json:"translation_id"`
	Name          string             `json:"name"`
	Complexity    pgtype.Int4        `json:"complexity"`
	PhotoKey      pgtype.Text        `json:"photo_key"`
	Gender        string             `json:"gender"`
	Paces         []int32            `json:"paces"`
	Popularity    int32              `json:"popularity"`
	Genres        []string           `json:"genres"`
	Handshakes    []string           `json:"handshakes"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type DanceRegion struct {
	ID        int64              `json:"id"`
	DanceID   int64              `json:"dance_id"`
	RegionID  int64              `json:"region_id"`
	CreatedAt time.Time          `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type DanceSong struct {
	ID        int64              `json:"id"`
	DanceID   int64              `json:"dance_id"`
	SongID    int64              `json:"song_id"`
	CreatedAt time.Time          `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type DanceVideo struct {
	ID        int64              `json:"id"`
	DanceID   int64              `json:"dance_id"`
	VideoID   int64              `json:"video_id"`
	CreatedAt time.Time          `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Region struct {
	ID            int64              `json:"id"`
	TranslationID pgtype.Int8        `json:"translation_id"`
	Name          string             `json:"name"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Song struct {
	ID            int64              `json:"id"`
	TranslationID pgtype.Int8        `json:"translation_id"`
	FileKey       string             `json:"file_key"`
	Name          string             `json:"name"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type SongArtist struct {
	ID        int64              `json:"id"`
	SongID    int64              `json:"song_id"`
	ArtistID  int64              `json:"artist_id"`
	CreatedAt time.Time          `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Translation struct {
	ID        int64              `json:"id"`
	EngName   pgtype.Text        `json:"eng_name"`
	RuName    pgtype.Text        `json:"ru_name"`
	ArmName   pgtype.Text        `json:"arm_name"`
	CreatedAt time.Time          `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Video struct {
	ID            int64              `json:"id"`
	Link          string             `json:"link"`
	TranslationID pgtype.Int8        `json:"translation_id"`
	Name          string             `json:"name"`
	Type          string             `json:"type"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
