// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	SearchDances(ctx context.Context, arg SearchDancesParams) ([]SearchDancesRow, error)
}

var _ Querier = (*Queries)(nil)
