// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateTranslations(ctx context.Context, arg []CreateTranslationsParams) (int64, error)
	Placeholder(ctx context.Context) (Translation, error)
}

var MyQuerier Querier = (*Queries)(nil)
