// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	Placeholder(ctx context.Context) (Translation, error)
}

var _ Querier = (*Queries)(nil)
