// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: regions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listRegions = `-- name: ListRegions :many
SELECT 
    r.id,
    COALESCE(
        CASE 
            WHEN $1::text = 'ru' THEN t.ru_name
            WHEN $1::text = 'en' THEN t.eng_name
            WHEN $1::text = 'arm' THEN t.arm_name
            ELSE r.name
        END, 
        r.name
    )::text AS name
FROM regions r
LEFT JOIN translations t ON r.translation_id = t.id
ORDER BY r.id
`

type ListRegionsRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) ListRegions(ctx context.Context, lang pgtype.Text) ([]ListRegionsRow, error) {
	rows, err := q.db.Query(ctx, listRegions, lang)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRegionsRow{}
	for rows.Next() {
		var i ListRegionsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
