// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: test.sql

package db

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT id, email, created_at FROM test_users
WHERE email = $1
`

func (q *Queries) GetUser(ctx context.Context, email string) (TestUser, error) {
	row := q.db.QueryRow(ctx, getUser, email)
	var i TestUser
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}
